@Backend_HostAddress = https://localhost:7010

GET {{Backend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Backend_HostAddress}}/api/user
Content-Type: application/json

{
  //User
}

###
